---
- hosts: awstest
  sudo: yes
  tasks:
    - name: Update
      apt: update_cache=yes

    - name: Update all packages to latest
      apt: upgrade=yes

    - name: Install git
      apt: name=git-core

    - name: get build essentials
      apt: name=build-essential

    - name: get python dev
      apt: name=python2.7-dev

    - name: Get setup tools
      apt: name=python-setuptools   
    
    - name: install pip
      easy_install: name=pip
 
    - name: Install virtualenv
      command: sudo pip install virtualenv
 
    - name: Create app directory
      file: path=/var/app recurse=yes state=directory

    - name: Create venv
      command: sudo virtualenv /var/app/venv 

    - name: Put public key on server
      copy: src=~/.ssh/id_rsa.pub dest=/var/app/id_rsa.pub mode=0644

    - name: Put private key on server
      copy: src=~/.ssh/id_rsa dest=/var/app/id_rsa mode=0600

    - name: Clone repo
      git: repo=ssh://git@github.com/hestinr12/hire_esquire_challenge.git accept_hostkey=yes dest=/var/app/hire_esquire_challenge key_file=/var/app/id_rsa

    - name: Install requirements
      pip: requirements=/var/app/hire_esquire_challenge/requirements.txt virtualenv=/var/app/venv
    
    - name: Install gcc
      apt: name=gcc

    - name: Install PCRE
      apt: name=libpcre3
 
    - name: Get uwsgi
      pip: name=uwsgi virtualenv=/var/app/venv

    - name: Migrate database
      command: sudo /var/app/venv/bin/python /var/app/hire_esquire_challenge/manage.py migrate
      # django_manage: command=migrate app_path=/var/app/hire_esquire_challenge

    - name: Run server
      command: sudo /var/app/venv/bin/uwsgi --ini /var/app/hire_esquire_challenge/devops/wsgi.ini
      # environment:
        # PATH: /var/app/venv/bin
