---
- hosts: awstest
  sudo: yes
  tasks:
    - name: Update
      apt: update_cache=yes

    - name: Update all packages to latest
      apt: upgrade=yes

    - name: install relevant packages
      apt: name={{ item }}
      with_items:
        - git-core
        - build-essential
        - python2.7-dev
        - python-setuptools
        - gcc
        - libpcre3
        - nginx
    
    - name: install pip
      easy_install: name=pip
 
    - name: Install virtualenv
      command: sudo pip install virtualenv
 
    - name: Create app directory
      file: path=/var/app recurse=yes state=directory

    - name: Create venv
      command: sudo virtualenv /etc/nginx/sites-available/venv 

    - name: Put repo public key on server
      copy: src=~/.ssh/id_rsa.pub dest=/var/app/id_rsa.pub mode=0644

    - name: Put repo private key on server
      copy: src=~/.ssh/id_rsa dest=/var/app/id_rsa mode=0600

    - name: Clone repo
      git: repo=ssh://git@github.com/hestinr12/hire_esquire_challenge.git version=nginx accept_hostkey=yes dest=/etc/nginx/sites-available/hire_esquire_challenge key_file=/var/app/id_rsa

    - name: Delete default nginx site-available
      file: path=/etc/nginx/sites-enabled/default state=absent

    - name: Copy our app conf into nginx/site-available
      command: sudo ln -sf /etc/nginx/sites-available/hire_esquire_challenge/devops/nginx_hire.conf /etc/nginx/sites-enabled/

    - name: Touch uwsgi trigger file 
      file: path=/etc/nginx/sites-available/hire_esquire_challenge/devops/uwsgi_reload.trigger state=touch

    - name: Install requirements
      pip: requirements=/etc/nginx/sites-available/hire_esquire_challenge/requirements.txt virtualenv=/etc/nginx/sites-available/venv
    
    - name: Get uwsgi
      pip: name=uwsgi virtualenv=/etc/nginx/sites-available/venv

    - name: Migrate database
      command: sudo /etc/nginx/sites-available/venv/bin/python /etc/nginx/sites-available/hire_esquire_challenge/manage.py migrate
      # django_manage: command=migrate app_path=/var/app/hire_esquire_challenge

    - name: Run server
      shell: sudo /etc/nginx/sites-available/venv/bin/uwsgi --touch-reload /etc/nginx/sites-available/hire_esquire_challenge/devops/uwsgi_reload.trigger --socket 0.0.0.0:8000 --protocol http --chdir /etc/nginx/sites-available/hire_esquire_challenge/ --wsgi-file /etc/nginx/sites-available/hire_esquire_challenge/main_site/wsgi.py
      async: 999999
      poll: 0

    - name: start nginx
      service: name=nginx state=started

    - name: reload nginx
      service: name=nginx state=restarted
