---
- hosts: awstest
  sudo: yes
  tasks:
    - name: Update all packages to latest
      yum: name=* state=latest

    - name: Install nginx
      yum: name=nginx state=latest  
    
    - name: Install dev tools
      yum: name=gcc state=latest
 
    - name: Start nginx
      service: name=nginx state=started

    - name: Install git
      yum: name=git state=latest
    
    - name: Install virtualenv
      yum: name=python-virtualenv state=latest
    
    - name: Create app directory
      file: path=/var/app recurse=yes state=directory

    - name: Create venv
      command: sudo /usr/bin/virtualenv /var/app/venv 

    - name: install uwsgi
      pip: name=uwsgi virtualenv=/var/app/venv

    - name: Put public key on server
      copy: src=~/.ssh/id_rsa.pub dest=/var/app/id_rsa.pub mode=0644

    - name: Put private key on server
      copy: src=~/.ssh/id_rsa dest=/var/app/id_rsa mode=0600

    - name: Clone repo
      git: repo=ssh://git@github.com/hestinr12/hire_esquire_challenge.git accept_hostkey=yes dest=/var/app/hire_esquire_challenge key_file=/var/app/id_rsa

    - name: Install requirements
      pip: requirements=/var/app/hire_esquire_challenge/requirements.txt virtualenv=/var/app/venv

    - name: Migrate database
      command: sudo /var/app/venv/bin/python /var/app/hire_esquire_challenge/manage.py migrate
      # django_manage: command=migrate app_path=/var/app/hire_esquire_challenge

    - name: Cp in site_enabled nginx.conf
      command: sudo cp /var/app/hire_esquire_challenge/devops/nginx_hire.conf /etc/nginx/conf.d/

    - name: Restart nginx
      service: name=nginx state=restarted

    - name: launch uwsgi
      command: sudo /var/app/venv/bin/uwsgi --socket :8000 --wsgi-file /var/app/hire_esquire_challenge/main_site/wsgi.py
      # environment:
        # PATH: /var/app/venv/bin
