---
- hosts: awstest
  sudo: yes
  tasks:
    - name: Update all packages to latest
      yum: name=* state=latest

    - name: Install nginx 
      yum: name=nginx state=present  
      notify:
        - start nginx

    - name: Start nginx
      service: name=nginx state=started
